name: Publish Package

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  verify-docs-version:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC
    steps:
      - name: Checkout stable branch
        uses: actions/checkout@v4
        with:
          ref: stable

      - name: Read version from pubspec.yaml
        id: stable_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | head -n1 | cut -d ' ' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Read version from index.html
        id: pages_version
        run: |
          VERSION=$(grep -oP 'due_date\s*\K[0-9]+\.[0-9]+\.[0-9]+' index.html | head -n1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare_versions
        run: |
          echo "Docs version: ${{ steps.pages_version.outputs.version }}"
          echo "Stable version: ${{ steps.stable_version.outputs.version }}"
          if [ "${{ steps.pages_version.outputs.version }}" != "${{ steps.stable_version.outputs.version }}" ]; then
            echo "Version mismatch!"
            echo "publish=false" >> $GITHUB_OUTPUT
            exit 1
          fi
          echo "Versions match."
          echo "publish=true" >> $GITHUB_OUTPUT

      - name: Setup dart
        if: steps.compare_versions.outputs.publish == 'true'
        uses: dart-lang/setup-dart@v1

      - name: Publish package
        if: steps.compare_versions.outputs.publish == 'true'
        run: |
          dart pub get
          dart pub publish -n
          dart pub publish -f
